### ISSUE TITLE
Allow detection of this mod running

### ISSUE THREAD

**Issue by xp-soaring** [leblancdavid/MSFSThermalSim#18]
For our multiplayer soaring, it's REALLY important to be able to detect a mod like this running so we can allow multiplayer task to use it, or not use it, in a controlled way. Obviously having some people running the mod on a task we've planned to be 'plain' MSFS is going to really mess up the results between different people.

What Kinetic Assist did was set ("FOLDING WING RIGHT PERCENT", "percent") to 1 when it was running, and we can detect that with other mods (e.g. our soaring-oriented logger) - it would be REALLY helpful if you could set that in MSFSThermalSim as well.

**Comment by leblancdavid** [comment]
The "FOLDING WING RIGHT PERCENT" sim var will now be set to 1.0 when thermal sim is running, and 0.0 when it's off. This change will be available in the next release.

**Comment by xp-soaring** [comment]
Awesome - thanks, that feature is really appreciated.
